apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
             memory: "64Mi"
             cpu: "250m"
  ---
apiVersion: v1
kind: Service
metadata:
  name: ngix-deployment-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ngix-dep-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 6
# [while true; do curl http://dervice-ip; done]
or
===========
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ngix-dep-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      selectPolicy: Max
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120
      selectPolicy: Max
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 25
        periodSeconds: 60

. The scaleUp section specifies that the HPA should wait for 300 seconds (5 minutes) before scaling up again, and it should use the maximum value from the policies. The policies state that the HPA can add up to 4 pods or increase the number of pods by 100% every 60 seconds.

. The scaleDown section specifies similar behavior for scaling down, with a stabilization window of 300 seconds and policies to remove up to 2 pods or decrease the number of pods by 50% every 60 seconds.                                 