apiVersion: v1
kind: PersistentVolume
metadata:
  name:  pv-appone
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeClaimPolicy: Recycle
  nfs:
     path: /appone
     sever: <nfs-ipaddress>

